### ISSUE TITLE
sadmin command not working

### ISSUE THREAD

**Issue by quackersian** [quackersian/server-starter#7]
Ignoring exception in command sadmin:
Traceback (most recent call last):
  File "C:\Users\Server\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Server\AppData\Local\Programs\Python\Python39\Production Discord Bots\server-starter-main\serverStarter.py", line 136, in squadAddAdmin
    file.append(textToAppend)
AttributeError: '_io.TextIOWrapper' object has no attribute 'append'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Server\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Server\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Server\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: '_io.TextIOWrapper' object has no attribute 'append'

**Comment by quackersian** [comment]
fixed in v11
